- trigger: "acceptance-tests"
  label: "Acceptance"
  build:
    commit: "${BUILDKITE_COMMIT}"
    branch: "${BUILDKITE_BRANCH}"
    env:
      TAG: "${BUILDKITE_BUILD_NUMBER}"
      RUN_DOCKER_BUILD: "false"
